/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftForm: typeof import('./src/components/LeftForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./src/components/Tree.vue')['default']
  }
}
